apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
spec:
  replicas: 4
  selector: 
    dc: IN
  template: 
    metadata:
      name: myrcpod
      labels:
        dc: IN
    spec:
      containers:
      - name: myweb
        image: vimal13/apache-webserver-php